stages:
  - tests
  - convert
  - csim
  - csynth
  - report

pytest:
  stage: tests
  image: gitlab-registry.cern.ch/fastmachinelearning/hls4ml-testing:0.1.base
  tags: 
    - docker
  before_script:
    - source ~/.bashrc
    - git submodule init
    - git submodule update
    - conda activate hls4ml-testing
    - pip install .[profiling]
  script:
    - cd ${CI_PROJECT_DIR}/test/pytest
    - pytest -rA $TEST --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: 
        - test/pytest/report.xml
    expire_in: 1 week
  allow_failure: true

test_qkeras:
  extends: pytest
  variables:
    TEST: test_qkeras.py

test_cnn_mnist:
  extends: pytest
  variables:
    TEST: test_cnn_mnist.py

test_softmax:
  extends: pytest
  variables:
    TEST: test_softmax.py

convert:
  stage: convert
  image: gitlab-registry.cern.ch/fastmachinelearning/hls4ml-testing:0.1.vivado
  tags: 
    - hls4ml
  before_script:
    - source ~/.bashrc
    - git submodule init
    - git submodule update
    - conda activate hls4ml-testing
    - pip install .[profiling]
  script:
    - cd ${CI_PROJECT_DIR}/test
    - ./convert-keras-models.sh -x -f keras-models.txt
  artifacts:
    paths:
    - test/vivado_prj/
    expire_in: 2 days

csim:
  stage: csim
  image: gitlab-registry.cern.ch/fastmachinelearning/hls4ml-testing:0.1.vivado
  tags: 
    - hls4ml
  before_script:
    - source ~/.bashrc
  script:
    - cd ${CI_PROJECT_DIR}/test
    - ./build-prj.sh -v 2019.2 -c -p 6
  artifacts:
    paths:
    - test/vivado_prj/
    expire_in: 2 days

csynth:
  stage: csynth
  image: gitlab-registry.cern.ch/fastmachinelearning/hls4ml-testing:0.1.vivado
  tags: 
    - hls4ml
  before_script:
    - source ~/.bashrc
  script:
    - cd ${CI_PROJECT_DIR}/test
    - ./build-prj.sh -v 2019.2 -s -r -p 6
  artifacts:
    paths:
    - test/vivado_prj/
    expire_in: 2 days

report:
  stage: report
  image: gitlab-registry.cern.ch/fastmachinelearning/hls4ml-testing:0.1.vivado
  tags: 
    - hls4ml
  before_script:
    - source ~/.bashrc
  script:
    - cd ${CI_PROJECT_DIR}/test
    - ./gather-reports.sh -b | tee report.rpt
  artifacts:
    when: always
    paths:
      - test/report.rpt
