stages:
  - first
  - csim
  - csynth
  - report

test:
  stage: first
  image: gitlab-registry.cern.ch/fastmachinelearning/hls4ml-testing:0.1.base
  tags: 
    - hls4ml
  before_script:
    - source ~/.bashrc
    - git submodule init
    - git submodule update
    - conda activate hls4ml-testing
    - pip install .[profiling]
  script:
    - cd ${CI_PROJECT_DIR}/test/pytest
    - pytest -rA --cov-report xml --cov=hls4ml --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: 
        - test/pytest/report.xml
        - test/pytest/coverage.xml

convert:
  stage: first
  image: gitlab-registry.cern.ch/fastmachinelearning/hls4ml-testing:0.1.vivado
  tags: 
    - hls4ml
  before_script:
    - source ~/.bashrc
    - git submodule init
    - git submodule update
    - conda activate hls4ml-testing
    - pip install .[profiling]
  script:
    - cd ${CI_PROJECT_DIR}/test
    - ./convert-keras-models.sh -x -f keras-models.txt

csim:
  stage: csim
  image: gitlab-registry.cern.ch/fastmachinelearning/hls4ml-testing:0.1.vivado
  tags: 
    - hls4ml
  before_script:
    - source ~/.bashrc
  script:
    - cd ${CI_PROJECT_DIR}/test
    - ./build-prj.sh -i /data/Xilinx -v 2019.2 -c -p 12

csynth:
  stage: csynth
  image: gitlab-registry.cern.ch/fastmachinelearning/hls4ml-testing:0.1.vivado
  tags: 
    - hls4ml
  before_script:
    - source ~/.bashrc
  script:
    - cd ${CI_PROJECT_DIR}/test
    - ./build-prj.sh -i /data/Xilinx -v 2019.2 -s -r -p 12 

report:
  stage: report
  image: gitlab-registry.cern.ch/fastmachinelearning/hls4ml-testing:0.1.vivado
  tags: 
    - hls4ml
  before_script:
    - source ~/.bashrc
  script:
    - cd ${CI_PROJECT_DIR}/test
    - ./gather-reports.sh -b | tee report.rpt
  artifacts:
    when: always
    paths:
      - test/report.rpt
