stages:
  - tests
  - convert
  - build

.pytest:
  stage: tests
  image: gitlab-registry.cern.ch/fastmachinelearning/hls4ml-testing:0.1.base
  tags: 
    - docker
  before_script:
    - source ~/.bashrc
    - git submodule init
    - git submodule update
    - conda activate hls4ml-testing
    - pip install .[profiling]
  script:
    - cd ${CI_PROJECT_DIR}/test/pytest
    - pytest -rA $TEST --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: 
        - test/pytest/report.xml
    expire_in: 1 week
  allow_failure: true

pytest test_qkeras:
  extends: .pytest
  variables:
    TEST: test_qkeras.py

pytest test_cnn_mnist:
  extends: .pytest
  variables:
    TEST: test_cnn_mnist.py

pytest test_softmax:
  extends: .pytest
  variables:
    TEST: test_softmax.py

convert:
  stage: convert
  image: gitlab-registry.cern.ch/fastmachinelearning/hls4ml-testing:0.1.base
  tags: 
    - docker
  before_script:
    - source ~/.bashrc
    - git submodule init
    - git submodule update
    - conda activate hls4ml-testing
    - pip install .[profiling]
  script:
    - cd ${CI_PROJECT_DIR}/test
    - ./convert-keras-models.sh -x -y -f keras-models.txt
  artifacts:
    paths:
    - test/vivado_prj/
    - test/convert-keras-models-ci.yml
    expire_in: 2 days

builds:
  stage: build
  needs: 
  - convert
  trigger:
    include:
      - job: convert
        artifact: test/convert-keras-models-ci.yml
    strategy: depend

