KerasJson: keras/hcal_dense_1.json
KerasH5:   keras/hcal_dense_1_weights.h5
InputData: keras/hcal_inputs.txt
OutputPredictions: keras/hcal_preds.txt
#TruthLabels: keras/KERAS_3layer_truth_labels.dat
OutputDir: ereg_v1
ProjectName: ereg_v1
XilinxPart: xcvu9p-fsgd2104-2-i
#XilinxPart: xcku115-flvb2104-2-i
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<32,14>
    ReuseFactor: 1
#  LayerType:
#    Dense:
#      ReuseFactor: 2
#      Strategy: Resource
#      Compression: True