KerasJson: keras/KERAS_mnist_mlp128.json
KerasH5:   keras/KERAS_mnist_mlp128_weights.h5
InputData: keras/KERAS_mnist_mlp128_input_features.dat
OutputPredictions: keras/KERAS_mnist_mlp128_predictions.dat
TruthLabels: keras/KERAS_mnist_mlp128_truth_labels.dat
OutputDir: my-hls-test-mnist-4096
ProjectName: myproject
#XilinxPart: xcvu9p-fsgd2104-2-i
XilinxPart: xcku115-flvb2104-2-i
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 4096
    Strategy: Resource
#  LayerName:
#    dense_1:
#      ReuseFactor: 112
