KerasJson: ../../example-models/keras/mnist_autoencoder.json
KerasH5:   ../../example-models/keras/mnist_autoencoder_weights.h5
#InputData: keras/KERAS_3layer_input_features.dat
#OutputPredictions: keras/KERAS_3layer_predictions.dat
OutputDir: mnist_autoencoder
ProjectName: mnist_autoencoder
XilinxPart: xcku115-flvb2104-2-i
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<18,8>
    ReuseFactor: 784
#  LayerType:
#    Dense:
#      ReuseFactor: 2
#      Strategy: Resource
#      Compression: True
