KerasJson: ../../example-models/keras/KERAS_mnist_>>>IMAGE_SHAPE<<<_mlp.json
KerasH5:   ../../example-models/keras/KERAS_mnist_>>>IMAGE_SHAPE<<<_mlp_weights.h5
InputData: ../../example-models/keras/KERAS_mnist_>>>IMAGE_SHAPE<<<_mlp_inputs.dat
OutputPredictions: ../../example-models/keras/KERAS_mnist_>>>IMAGE_SHAPE<<<_mlp_outputs.dat
TruthLabels: ../../example-models/keras/KERAS_mnist_>>>IMAGE_SHAPE<<<_mlp_truth_labels.dat
OutputDir: mnist_>>>IMAGE_SHAPE<<<_fxd_>>>WORD_SIZE<<<_>>>INTEGER_SIZE<<<_mlp
ProjectName: mnist_mlp
XilinxPart: xcku115-flvb2104-2-i
ClockPeriod: 10

IOType: io_parallel # options: io_serial/io_parallel
HLSConfig:
  Model:
    Precision: >>>DATA_TYPE<<<
    ReuseFactor: 1
    Strategy: Resource
    Compression: False
  LayerName:
    dense_1:
      ReuseFactor: >>>PIXEL_COUNT<<<
      Strategy: Resource
      Compression: False
    dense_2:
      ReuseFactor: 64
      Strategy: Resource
      Compression: False
    dense_3:
      ReuseFactor: 64
      Strategy: Resource
      Compression: False
