KerasJson: ../../example-models/keras/svhn_grayscale_mlp.json
KerasH5:   ../../example-models/keras/svhn_grayscale_mlp_weights.h5
InputData: ../../example-models/keras/svhn_grayscale_mlp_input_features.dat
OutputPredictions: ../../example-models/keras/svhn_grayscale_mlp_input_features.dat
OutputDir: my-hls-test
ProjectName: myproject
XilinxPart: xc7vx690tffg1927-2
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<18,8>
    ReuseFactor: 1024
    Strategy: Resource
#  LayerType:
#    Dense:
#      ReuseFactor: 2
#      Strategy: Resource
#      Compression: True
