KerasJson: example-keras-model-files/KERAS_1layer.json
KerasH5:   example-keras-model-files/KERAS_1layer_weights.h5
OutputDir: my-hls-dir-test

IOType: io_parallel # options: io_serial/io_parallel
ReuseFactor: 1 
DefaultPrecision: ap_fixed<18,8> 
