KerasJson: example-keras-model-files/KERAS_3layer.json
KerasH5:   example-keras-model-files/KERAS_3layer_95pruned_retrained_weights.h5
OutputDir: my-hls-test
ProjectName: myproject
XilinxPart: xc7vx690tffg1927-2
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
ReuseFactor: 1
Compression: 1 # options: 1 enable data compression, 0 otherwise
MaxIndexWordSize: 14 # as a rule of thumb, the sum of this value and the word size of the default precision should be 32
DefaultPrecision: ap_fixed<18,8>
