KerasJson: example-keras-model-files/KERAS_3layer.json
KerasH5:   example-keras-model-files/KERAS_3layer_70pruned_retrained_weights.h5
OutputDir: my-hls-test
ProjectName: myproject
XilinxPart: xc7vx690tffg1927-2
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
ReuseFactor: 16
Compression: 1 # options: 1 enable data compression, 0 otherwise
MaxIndexWordSize: 7 # as a rule of thumb, the sum of this-value-time-2 and the word size of the default precision should be 32 = (7*2)+18
DefaultPrecision: ap_fixed<18,8>
