KerasJson: example-keras-model-files/KERAS_3layer.json
KerasH5:   example-keras-model-files/KERAS_3layer_95pruned_retrained_weights.h5
OutputDir: my-hls-test
ProjectName: myproject
XilinxPart: xc7vx690tffg1927-2
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
ReuseFactor: 1
DefaultPrecision: ap_fixed<18,8>
Compression: 1 # options: 1 enable data compression, 0 otherwise
MaxIndexWordSize: 7 # number of bits to encode each index when compression is enabled, ignored otherwise
