# KerasJson: example-keras-model-files/KERAS_1layer.json
# KerasH5:   example-keras-model-files/KERAS_1layer_weights.h5
KerasJson: example-keras-model-files/KERAS_3layer.json
KerasH5:   example-keras-model-files/KERAS_3layer_weights.h5
#KerasJson: example-keras-model-files/KERAS_dense_16x100x100x100x100x100x5.json
#KerasH5:   example-keras-model-files/KERAS_dense_16x100x100x100x100x100x5_weights.h5
#OutputDir: hls-6layer100s-reuse100
OutputDir: hls-3layer-reuse9-noalloc-noreshape
ProjectName: myproject
XilinxPart: xcku115-flvb2104-2-i
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
ReuseFactor: 9
DefaultPrecision: ap_fixed<16,6> 
