#KerasJson: example-keras-model-files/KERAS_3layer.json
#KerasH5:   example-keras-model-files/KERAS_3layer_weights.h5
#OutputDir: KERAS_3layer

#KerasJson: example-keras-model-files/KERAS_dense_16x100x100x100x100x100x5.json
#KerasH5:   example-keras-model-files/KERAS_dense_16x100x100x100x100x100x5_weights.h5
#OutputDir: KERAS_dense_16x100x100x100x100x100x5

KerasJson: example-keras-model-files/KERAS_mnist_mlp.json
KerasH5:   example-keras-model-files/KERAS_mnist_mlp_weights.h5
OutputDir: KERAS_mnist_mlp

#KerasJson: example-keras-model-files/KERAS_reuters_mlp.json
#KerasH5:   example-keras-model-files/KERAS_reuters_mlp_weights.h5
#OutputDir: KERAS_reuters_mlp

#KerasJson: example-keras-model-files/KERAS_digit_recognizer_mlp.json
#KerasH5:   example-keras-model-files/KERAS_digit_recognizer_mlp_weights.h5
#OutputDir: KERAS_digit_recognizer_mlp

ProjectName: myproject
XilinxPart: xcku115-flvb2104-2-i
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
ReuseFactor: 2000
DefaultPrecision: ap_fixed<32,16>
