KerasJson: example-keras-model-files/2layer_100x100.json
KerasH5:   example-keras-model-files/2layer_100x100.h5
OutputDir: hls-2layer100s-reuse50
ProjectName: myproject
XilinxPart: xcku115-flvb2104-2-i
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
ReuseFactor: 50
DefaultPrecision: ap_fixed<16,6> 
