#KerasJson: example-keras-model-files/KERAS_dense_16x100x100x100x100x100x5.json
#KerasH5:   example-keras-model-files/KERAS_dense_16x100x100x100x100x100x5_weights.h5
KerasJson: example-keras-model-files/KERAS_3layer.json
KerasH5:   example-keras-model-files/KERAS_3layer_weights.h5
OutputDir: hls-test-phil-3layer-reuse8-lutram
ProjectName: myproject
XilinxPart: xcku115-flvb2104-2-i
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
ReuseFactor: 8
DefaultPrecision: ap_fixed<16,6> 